[project]
name = "mcp-databricks-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "databricks-langchain>=0.4.2",
    "databricks-sdk>=0.50.0",
    "httpx>=0.28.1",
    "mcp-use>=1.2.7",
    "mcp[cli]>=1.6.0",
]
